version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - echo "Build starter..."
      # Det interne systemet kjører sin store IF-setning her.
      # Vi trenger bare å sørge for at vi er klare.
artifacts:
  base-directory: app/dist
  files:
    - '**/*'
