version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - cd app && npm install
  build:
    commands:
      - echo "Kjører build for APP_TYPE server..."
      - cd app && npm run build
      - echo "Build fullført. Innhold i dist:"
      - ls -l ../dist
artifacts:
  base-directory: dist
  files:
    - '**/*'
